### ISSUE TITLE
Having trouble running code in Visual Studio

### ISSUE THREAD

**Issue by G1Lburt** [NaughtyZZ/3D_face_dense_registration#3]
I just started learning how to code and I'm sorry if these questions are dumb :(
I was running the code in VS and this happened:
![image](https://github.com/NaughtyZZ/3D_face_dense_registration/assets/139319546/c099d6f3-39b1-4899-be8c-af794d568660)
This is the code where the error occurred (I added std::cout << "correct" << std::endl;: to detect error):
![image](https://github.com/NaughtyZZ/3D_face_dense_registration/assets/139319546/4cb5c75b-ce2d-46fa-bcae-1c5f94914cd9)
Can you hint me on what went wrong?
And for clarification, should I put template.ply here: 
![image](https://github.com/NaughtyZZ/3D_face_dense_registration/assets/139319546/c80ac802-dd3d-40c5-9117-705020975230)
and put file path here:
![image](https://github.com/NaughtyZZ/3D_face_dense_registration/assets/139319546/9633d244-240e-4d7a-8876-db2baf51c278)

**Comment by NaughtyZZ** [comment]
> I just started learning how to code and I'm sorry if these questions are dumb :( I was running the code in VS and this happened: ![image](https://user-images.githubusercontent.com/139319546/252901667-c099d6f3-39b1-4899-be8c-af794d568660.png) This is the code where the error occurred (I added std::cout << "correct" << std::endl;: to detect error): ![image](https://user-images.githubusercontent.com/139319546/252901958-4cb5c75b-ce2d-46fa-bcae-1c5f94914cd9.png) Can you hint me on what went wrong? And for clarification, should I put template.ply here: ![image](https://user-images.githubusercontent.com/139319546/252905491-c80ac802-dd3d-40c5-9117-705020975230.png) and put file path here: ![image](https://user-images.githubusercontent.com/139319546/252906180-9633d244-240e-4d7a-8876-db2baf51c278.png)

你好，命令参数我是这样设置的，文件目录见“./demo/  ”文件夹 template.ply 放的应该没问题，有问题请随时提出，谢谢！
![36c42ad26a9578c63c51f940ed1c5d4](https://github.com/NaughtyZZ/3D_face_dense_registration/assets/40814253/6bb780fa-a967-442d-9df5-d66726ef1129)

**Comment by NaughtyZZ** [comment]
另外这个依赖于eigen库和MKL库，后面我会把这些依赖说明加上去，我看你这里似乎是没有安装eigen库的问题

**Comment by G1Lburt** [comment]
谢谢，我安装了Eigen库和MKL库。问题似乎出现在initialization上
![image](https://github.com/NaughtyZZ/3D_face_dense_registration/assets/139319546/093af37b-1cd9-4a20-8670-ab6258ef7ed2)
this->points(N_v, 3); 处会报错。

**Comment by NaughtyZZ** [comment]
eigen版本可能不支持矩阵size为0的初始化？这几行其实可以注释掉，也可以根据报错debug一下

**Comment by G1Lburt** [comment]
非常感谢您。现在可以运行了
