### ISSUE TITLE
Cannot compile facedenseregister.cpp

### ISSUE THREAD

**Issue by qaz8788817** [NaughtyZZ/3D_face_dense_registration#5]
Hi, I have some problem with using VS2019 to compile facedenseregister.cpp in VC++(with initializations by NICP).
And my dependencies are all latest version.
Here is the error output:
![image](https://github.com/NaughtyZZ/3D_face_dense_registration/assets/73918947/970d4c9e-7233-43b1-8e86-bad28a4d0105)
And it also show some warnings about:
![image](https://github.com/NaughtyZZ/3D_face_dense_registration/assets/73918947/f816338b-2ce8-41c4-8086-dbb74cb01620)

Would you mind to provide your libigl source code for me?
I can't thank you enough.

**Comment by NaughtyZZ** [comment]
I have already compiled theprogram into a *.exe demo. Here is the igl package I use. 
[igl.zip](https://github.com/NaughtyZZ/3D_face_dense_registration/files/13839759/igl.zip)

**Comment by qaz8788817** [comment]
> I have already compiled theprogram into a *.exe demo. Here is the igl package I use. [igl.zip](https://github.com/NaughtyZZ/3D_face_dense_registration/files/13839759/igl.zip)

But after I execute like this:
![image](https://github.com/NaughtyZZ/3D_face_dense_registration/assets/73918947/545df84f-bf2b-4c6c-9379-0a385136fb23)

And nothing happened. I don't know why.

Here is the executable file's folder:
![image](https://github.com/NaughtyZZ/3D_face_dense_registration/assets/73918947/5642bccb-7880-45f9-83ea-18f997c29a8f)

Thank you.

**Comment by NaughtyZZ** [comment]
I test it just now in several computers and it's OK in the Windows system. The excutation path should be a pure English one? Is the VS runtime environment compatible? You may need some time to debug the source files in other systems. 
![无标题](https://github.com/NaughtyZZ/3D_face_dense_registration/assets/40814253/0f3a56d7-1823-4aea-b8c2-962995b8c010)

**Comment by qaz8788817** [comment]
> I test it just now in several computers and it's OK in the Windows system. The excutation path should be a pure English one? Is the VS runtime environment compatible? You may need some time to debug the source files in other systems.我剛剛在幾台電腦上測試了一下，在Windows系統中是沒問題的。執行路徑應該是純英文的吧？ VS運作環境是否相容？您可能需要一些時間來調試其他系統中的來源檔案。 ![无标题](https://private-user-images.githubusercontent.com/40814253/294445276-0f3a56d7-1823-4aea-b8c2-962995b8c010.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NDYxMzQsIm5iZiI6MTcwNDQ0NTgzNCwicGF0aCI6Ii80MDgxNDI1My8yOTQ0NDUyNzYtMGYzYTU2ZDctMTgyMy00YWVhLWI4YzItOTYyOTk1YjhjMDEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA5MTAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4MGI0MDQyNzQyMzMyMGZiZGNkZTFkM2NlYjk4YjcyZmEwNmM5OThhYzNmMGRlNGI4MDZmMTMwM2NjZWYzYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FcOOREIk30-KBiUlnHB1omq_oB-ez6gvaEJGkUifdiM)

Yes, the path is all English. I will try to fix VS runtime environment.
Thanks for your help! *^____^*

**Comment by qaz8788817** [comment]
Sorry to bother you again.
I've installed the depandencies for several times, and I still cannot install them successfully.
Could you please tell me more details about the VS runtime environment?

Thank you.

**Comment by NaughtyZZ** [comment]
Mine is window 10, x64,  vs2015. I think these details are not useful to you. Does you environment support other programs?

**Comment by qaz8788817** [comment]
My machine is like a new computer of Windows 10.
Could you please tell me what I need to install or pay attention to before I run the *.exe?
And how did you install them? I have installed MKL(using .exe from intel), Eigen(I tried vcpkg. In the VS2019, I can run a simple Eigen program), but I cannot compile libigl success in CMAKE.

Thank you.

**Comment by NaughtyZZ** [comment]
So the problem is that the igl library is not successfully installed. The runtime environment for vs2019 （some *dll files） may differ from vs2015， so you need either to compile the source file first in you environment (I guess) or use some other *dll files (compatible to vs2015) to run the *exe demo.

**Comment by qaz8788817** [comment]
Execeuse me. Here is my steps for using CMAKE in libigl.

1. I clone the libigl in my desktop and use system administrator to open CMake.
2. Check the source code path is "C:/User/xxx/Desktop/libigl", and build path is "C:/User/xxx/Desktop/libigl/build".
3. Run configure, then it shows me some warning like:
![image](https://github.com/NaughtyZZ/3D_face_dense_registration/assets/73918947/e7b71e04-1496-4ee1-a38f-80fbb8da2315)
and
![image](https://github.com/NaughtyZZ/3D_face_dense_registration/assets/73918947/e626bc48-7575-4194-abf0-c04a7d8e6be5)
4. Then I use these ways to fix them:
![image](https://github.com/NaughtyZZ/3D_face_dense_registration/assets/73918947/57b8b705-5a49-4617-a198-e036329ab8a5)
and
![image](https://github.com/NaughtyZZ/3D_face_dense_registration/assets/73918947/39f7a4bf-828d-44e1-a79f-22851ae03fb4)
5. Delete the cache and configure again. It shows me configuration is done.
6. Then, I generate it. 

After above steps, I go to the CMake prefix path such like "C:/Program Files (x86)/libigl", there is no folder named like this in Program Files (x86). And the "external" folder does not appear.

Does this mean I failed in CMake?

Thank you.

**Comment by NaughtyZZ** [comment]
I am not good at debugging this issue. I suggest that you can refer to the orignial tutorial at [[Libigi](https://libigl.github.io/tutorial/)](https://libigl.github.io/tutorial/) or ask problem at the original project [https://github.com/libigl/libigl](https://github.com/libigl/libigl). I can see in the tutorial that the igl library are not compatible with x86 programs.
![image](https://github.com/NaughtyZZ/3D_face_dense_registration/assets/40814253/dccc99ca-4a08-4fe9-a4d7-9f6f6dec82a6)

**Comment by qaz8788817** [comment]
Okay, thanks for your help. I repost my question to the original project.
