### ISSUE TITLE
About run *.exe

### ISSUE THREAD

**Issue by qaz8788817** [NaughtyZZ/3D_face_dense_registration#6]
Hi, now my computer can use VS2019 to compile and execute the tutorial file in libigl, the simple Eigan3 program (for testing), and the simple MKL program (for testing), respectively.
But I still can't use the *.exe directly. Does it need to be executed in any special way? Or do I need to add certain paths to the system environment variables?

Thanks for your help.

**Comment by NaughtyZZ** [comment]
The *exe is compiled with VS 2015 environments. You can recompile an *.exe file with your VS 2019 and then you can run it on your computer.

**Comment by qaz8788817** [comment]
> The *exe is compiled with VS 2015 environments. You can recompile an *.exe file with your VS 2019 and then you can run it on your computer.

Thank you. I will try to compile it!!

**Comment by qaz8788817** [comment]
Hi, Could you tell me which option you choose to build?
![image](https://github.com/NaughtyZZ/3D_face_dense_registration/assets/73918947/5abbeec3-19a6-4db3-ae6a-7dce3c2946a7)
I've tried "No", and it cannot build because mkl_pardiso.h can't open. 
When I choose Parallel, it can build successfully but can't run. 
It's the error of picture when I double click the *.exe:
![image](https://github.com/NaughtyZZ/3D_face_dense_registration/assets/73918947/70fc94f1-8e61-41ed-8bd8-f39998406fad)
and I type the command in the powershell but nothing happen.

And when I choose Sequential, it is same above but the error message is:
![image](https://github.com/NaughtyZZ/3D_face_dense_registration/assets/73918947/e2c5176b-d54d-488c-a849-7dc9bfa69b0b)
The last one Cluster cannot build successfully because it can't open impi.lib file.

Did I miss some important information or action?

Thanks for your help!!!!

**Comment by NaughtyZZ** [comment]
Mine is sequencial. The problem shows that some dynamic libraries of MKL are missing.

**Comment by qaz8788817** [comment]
I download mkl_sequential.2.dll from website DLLme and put it in "C:\Windows\System32\".
And there is another error: 
![image](https://github.com/NaughtyZZ/3D_face_dense_registration/assets/73918947/e759edb5-db70-4cb4-8267-7aba5a0e6c4c)
Here is the error code:
![image](https://github.com/NaughtyZZ/3D_face_dense_registration/assets/73918947/4db48f8d-7880-447b-a0bb-a0c063a9ac25)

Thanks for your help.

**Comment by NaughtyZZ** [comment]
I suggest you should locate the code line of the error first.

**Comment by qaz8788817** [comment]
> I suggest you should locate the code line of the error first.

Emm.. I found something weird. I think maybe it's another problem. Iwill ask intel community if there is any solution. 
![image](https://github.com/NaughtyZZ/3D_face_dense_registration/assets/73918947/8c81dec8-9493-4b5b-b0ad-62c4df30ea71)

When I build the project, it always show me no error but some warning: 
![image](https://github.com/NaughtyZZ/3D_face_dense_registration/assets/73918947/db360495-5415-4d27-9992-e7c6ee2723db)
Does this matter?


And I use "Line-by-line execute" (shortcut key is F11) to try to find the error code line. 
It stop here and I don't know how to fix it.
![image](https://github.com/NaughtyZZ/3D_face_dense_registration/assets/73918947/2dcb05b7-40f8-480d-9caa-44e066f80e2a)
In the main function, it stop here:
![image](https://github.com/NaughtyZZ/3D_face_dense_registration/assets/73918947/e6246f06-270f-46df-9a6f-2f888669bf0f)

Thank you. Hope that it doesn't inconvenience you too much.

**Comment by NaughtyZZ** [comment]
You may try to delete these lines and it will not affect the whole program.
![image](https://github.com/NaughtyZZ/3D_face_dense_registration/assets/40814253/7f49831d-b70e-4735-92b3-ead618fc8726)

**Comment by qaz8788817** [comment]
Hi, I take your suggestion to delete these lines.
![image](https://github.com/NaughtyZZ/3D_face_dense_registration/assets/73918947/2294d55c-b04f-4b5d-8a49-48612574a579)
And it can successfully load template.ply now. 
But it will break and show this line:
![image](https://github.com/NaughtyZZ/3D_face_dense_registration/assets/73918947/7851444f-e4be-4fe0-8078-fd7478d982f5)
Here is the error code:
![image](https://github.com/NaughtyZZ/3D_face_dense_registration/assets/73918947/1cc968cf-b0fa-4fac-a0fd-1ef05354d697)
And the main function:
![image](https://github.com/NaughtyZZ/3D_face_dense_registration/assets/73918947/11f98b0f-47d7-4349-ad8d-ba00ebc7db6e)

I've searched Internet and they said this error code means "input inconsistent". Which input parameter do you think will cause this problem?

Thanks.

**Comment by NaughtyZZ** [comment]
I am not sure. You may check the input  variable and referring to the original manual of PARDISO function.  This line actually works as a simple sparse matrix factorization.

**Comment by qaz8788817** [comment]
> I am not sure. You may check the input variable and referring to the original manual of PARDISO function. This line actually works as a simple sparse matrix factorization.

Emm...I have this problem on my local computer, but not on the VM. It's weird. I think it's the version issue. My local computer is VS2022 but VM is VS2019.
But I can run the *.exe in my VM.
I have a question for the input files. The TU-models I downloaded from FaceScape are all ends with *.obj.
So I have to change them into *.ply. Do I need to set some special attribute when I use meshlab to export them as *.ply files?
Because I got something wrong. I exported a test file from meshlab, and I put it into inputfile to run register. Here is the process output:
![image](https://github.com/NaughtyZZ/3D_face_dense_registration/assets/73918947/36df4402-9f01-49cb-81e0-138c360b3e70)
And 1_neutral.ply can't open.
This is the setting when I use meshlab to export 1_neutral.obj as 1_neutral.ply. 
![image](https://github.com/NaughtyZZ/3D_face_dense_registration/assets/73918947/6d4aae99-a190-4b4d-847e-3b3a365c3bf7)

Thank you.

**Comment by NaughtyZZ** [comment]
I suggest that you can select all except for the TexCoord and binary encoding. There are many open libraries that can read general *.obj or *.ply files, e.g. libigl, openmesh, supporting batch data processing in this way. You can also refer to my code for reading *.ply and alter them for reading *.obj file.

**Comment by NaughtyZZ** [comment]
Here is my code for converting *obj files to *ply files.
[objFileReader.zip](https://github.com/NaughtyZZ/3D_face_dense_registration/files/13946930/objFileReader.zip)

**Comment by qaz8788817** [comment]
Thank you for providing such helpful guidance that helped me successfully run the program. Your assistance has been awesome!
