### ISSUE TITLE
How is the weights.txt generated? (For c++ "from scratch" version)

### ISSUE THREAD

**Issue by LPHFAQ** [NaughtyZZ/3D_face_dense_registration#7]
Hello! I just succeeded in running the [VC++(from scratch)], now I want to try my own scanning face mesh data with your excellent work. But I'm confused about how the weights.txt is generated. Could you please tell me how to get this weithts txt file? It seems that there is some kind of operation on geodesic distance to generate the weights.

**Comment by NaughtyZZ** [comment]
It is an array sized NX30, where N is the number of vertices and 30 is the number of landmarks. Each element is inversely proportional to the squared distance between each landmark and each vertex.

You can also refer to the matlab version (*demo_dense_registration.m Line 79-94* ), where Dfield.mat is a matrix of which each element is the geodesic distance from each point to each landmark on the template. I precompute it using a heat-flow based method [Crane et al. ACM TOG 2013. Geodesics in heat: A new approach to computing distance based on heat flow]. Other method for the computation of geodesic distance is OK. It only requires to be computed once only on the template.

**Comment by LPHFAQ** [comment]
> It is an array sized NX30, where N is the number of vertices and 30 is the number of landmarks. Each element is inversely proportional to the squared distance between each landmark and each vertex.
> 
> You can also refer to the matlab version (_demo_dense_registration.m Line 79-94_ ), where Dfield.mat is a matrix of which each element is the geodesic distance from each point to each landmark on the template. I precompute it using a heat-flow based method [Crane et al. ACM TOG 2013. Geodesics in heat: A new approach to computing distance based on heat flow]. Other method for the computation of geodesic distance is OK. It only requires to be computed once only on the template.

I find that the element in weights.txt equals to 1/(geodesic_distansce)^4, where the geodesic_distansce is the elements in Dfield.mat, is it right?

**Comment by NaughtyZZ** [comment]
I remember that it is right. You can test and verify it.

**Comment by NaughtyZZ** [comment]
There are also some tricks to avoid to denominator to be zero.

**Comment by LPHFAQ** [comment]
> There are also some tricks to avoid to denominator to be zero.

Thanks for your reply! I still have another question. I find that the c++ library "libigl" can also compute geodesic distansce (function igl::exact_geodesic). So I try to use igl::exact_geodesic to compute geodesic distansce from all points to the 30 landmarks on your template.ply. But the computing results are different from that of "computeGeodesicTemplate.m" in your project. Shown as follows, P1 is your result, and P2 is my result using igl::exact_geodesic.
![image](https://github.com/NaughtyZZ/3D_face_dense_registration/assets/57347617/272adcab-35ee-468a-bc0d-93c1b7b34938)
![image](https://github.com/NaughtyZZ/3D_face_dense_registration/assets/57347617/68477195-80b3-48a1-a5d9-c93b3701b4b4)
Is there any difference between your method and libigl's method of computing  geodesic distansce?
By the way, I find some codes seem like post processing in computeGeodesicTemplate.m as the following figure:
![image](https://github.com/NaughtyZZ/3D_face_dense_registration/assets/57347617/f969467b-0e50-410e-85e1-ae33ac840936)
Could please explain whether these codes have any specific meaning? I'm confused about what these codes mean.

**Comment by NaughtyZZ** [comment]
1. Although the results are not the same, they are proportional to each other. I think that both of these codes are OK.  The final value of geodistance is commonly affected by different algorithms and implementations. In my work, the geodistance is only required to be computed roughly rather than accurately.

2. The former means to reverse the value, since the program computes the heat value rather than the geodesic distance. The latter is to correct the geodesic distances. Since the distance from A to B is the same to B to A,  I get the average.  Also, the geodistance from any points to themselves should be zero. 

I hope that the above text can address you question. Thank you for you attention.

**Comment by LPHFAQ** [comment]
> 1. Although the results are not the same, they are proportional to each other. I think that both of these codes are OK.  The final value of geodistance is commonly affected by different algorithms and implementations. In my work, the geodistance is only required to be computed roughly rather than accurately.
> 2. The former means to reverse the value, since the program computes the heat value rather than the geodesic distance. The latter is to correct the geodesic distances. Since the distance from A to B is the same to B to A,  I get the average.  Also, the geodistance from any points to themselves should be zero.
> 
> I hope that the above text can address you question. Thank you for you attention.

Hi! I tried to use the geodistance computed by libigl and I found the align result is the same with yours. I think your reply is just right! Thanks for your patient reply!
